apiVersion: apps/v1
kind: Deployment
metadata:
  name: prowlarr
  namespace: media-server
spec:
  selector:
    matchLabels:
      app: prowlarr
  strategy:
    type: Recreate # This makes sure only one instance is running at a time
  template:
    metadata:
      labels:
        app: prowlarr
    spec:
      initContainers:
        - name: init-config
          image: dibi/envsubst:1
          command: ['sh', '-c', "envsubst < /tmp/config/config.template.xml > /config/config.xml"]
          env:
            - name: POSTGRES_HOST
              value: 'media-server-cluster'
            - name: POSTGRES_PORT
              value: '5432'
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: prowlarr-owner.media-server-cluster.credentials.postgresql.acid.zalan.do
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: prowlarr-owner.media-server-cluster.credentials.postgresql.acid.zalan.do
                  key: password
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: prowlarr-apikey
                  key: apikey
          volumeMounts:
            - name: configmap-volume
              mountPath: /tmp/config
            - name: config-pv
              mountPath: /config
      containers:
        - name: prowlarr
          image: lscr.io/linuxserver/prowlarr:1.27.0
          env:
            - name: PUID
              value: "100"
            - name: PGID
              value: "100"
            - name: TZ
              value: America/New_York
          ports:
            - containerPort: 8080
              name: http
          volumeMounts:
            - name: config-pv
              mountPath: /config
      securityContext:
        fsGroup: 100
        fsGroupChangePolicy: "OnRootMismatch"
        seccompProfile:
          type: RuntimeDefault
      volumes:
        - name: config-pv
          persistentVolumeClaim:
            claimName: prowlarr-config
        - name: configmap-volume
          configMap:
            name: prowlarr-config
