apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: whisparr-config
  namespace: media-server
  labels:
    app.kubernetes.io/instance: whisparr
    app.kubernetes.io/name: whisparr
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 250Gi
  storageClassName: wavecat