apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kavita-config
  namespace: media-server
  labels:
    app.kubernetes.io/instance: kavita
    app.kubernetes.io/name: kavita
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 250Gi
  storageClassName: wavecat