apiVersion: apps/v1
kind: Deployment
metadata:
  name: samba
  namespace: media-server
spec:
  selector:
    matchLabels:
      app: samba
  strategy:
    type: Recreate # This makes sure only one instance is running at a time
  template:
    metadata:
      labels:
        app: samba
    spec:
      containers:
        - name: samba
          image: servercontainers/samba
          env:
            - name: SAMBA_VOLUME_CONFIG_share
              value: |
                [share];path = /smbshare/;browsable = yes; read only = yes; guest ok = yes; read list = guest nobody; comment = Media
          ports:
            - containerPort: 445
              name: samba
          volumeMounts:
            - mountPath: /smbshare
              name: data-pv
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
      volumes:
        - name: data-pv
          persistentVolumeClaim:
            claimName: media-pvc-2
