apiVersion: apps/v1
kind: Deployment
metadata:
  name: samba
  namespace: media-server
spec:
  selector:
    matchLabels:
      app: samba
  template:
    metadata:
      labels:
        app: samba
    spec:
      containers:
      - name: samba
        image: servercontainers/samba
        env:
        - name: SAMBA_VOLUME_CONFIG_share 
          value: path = /smbshare/;browsable = yes; read_only = yes; guest ok = yes;
        ports:
        - containerPort: 445
          name: samba
        volumeMounts:
        - mountPath: /smbshare
          name: data-pv
      volumes:
        - name: data-pv
          persistentVolumeClaim:
            claimName: media-pvc-2
