apiVersion: apps/v1
kind: Deployment
metadata:
  name: samba
  namespace: media-server
spec:
  selector:
    matchLabels:
      app: samba
  template:
    metadata:
      labels:
        app: samba
    spec:
      containers:
      - name: samba
        image: dperson/samba
        env:
        - name: PERMISSIONS 
          value: "0777"     
        args:
        - "-s"
        - "share;/smbshare/;yes;yes;yes;none;none"
        ports:
        - containerPort: 445
        volumeMounts:
        - mountPath: /smbshare
          name: data-pv
      volumes:
        - name: data-pv
          persistentVolumeClaim:
            claimName: media-pvc-2
