apiVersion: v1
type: Opaque
kind: Secret
metadata:
  name: grafana-creds
  namespace: monitoring
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: admin-password
    secret-generator.v1.mittwald.de/encoding: hex
    secret-generator.v1.mittwald.de/length: "16"
stringData:
  admin-user: admin