apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config-pvc
  namespace: media-server
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 16Ti
  storageClassName: ""
  volumeMode: Filesystem
  volumeName: config-volume
