apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nzbhydra2-config
  namespace: media-server
  labels:
    app.kubernetes.io/instance: nzbhydra2
    app.kubernetes.io/name: nzbhydra2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 250Gi
  storageClassName: wavecat