apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  app.kubernetes.io/instance: nzbhydra2
  app.kubernetes.io/name: nzbhydra2
  name: nzbhydra2-config
  namespace: media-server
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 250Gi
  storageClassName: wavecat