apiVersion: apps/v1
kind: Deployment
metadata:
  name: vandam
  namespace: vandam-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vandam
  strategy:
    type: Recreate # This makes sure only one instance is running at a time
  template:
    metadata:
      labels:
        app: vandam
    spec:
      containers:
      - name: vandam
        image: ghcr.io/manyfold3d/manyfold:0.57.2
        env:
        - name: DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: vandam-owner.vandam-cluster.credentials.postgresql.acid.zalan.do
              key: username
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: vandam-owner.vandam-cluster.credentials.postgresql.acid.zalan.do
              key: password
        - name: DATABASE_URL
          value: postgresql://$(DATABASE_USER):$(DATABASE_PASSWORD)@vandam-cluster:5432/vandam
        - name: SECRET_KEY_BASE
          valueFrom:
            secretKeyRef:
              name: vandam-creds
              key: password
        - name: REDIS_URL
          value: redis://vandam-redis/1
        ports:
        - containerPort: 3214
          name: http
        volumeMounts:
        - name: data-pv
          mountPath: /libraries
      volumes:
      - name: data-pv
        persistentVolumeClaim:
          claimName: vandam-data
          