apiVersion: redis.redis.opstreelabs.in/v1beta1
kind: Redis
metadata:
  name: vandam-redis
  labels:
    app.kubernetes.io/name: vandam-redis
    app.kubernetes.io/instance: vandam-redis
    app.kubernetes.io/component: middleware
spec:
  kubernetesConfig:
    image: quay.io/opstree/redis:v6.2
    imagePullPolicy: IfNotPresent
  storage:
    volumeClaimTemplate:
      spec:
        storageClassName: wavecat
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi