apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  app.kubernetes.io/instance: nextcloud
  app.kubernetes.io/name: nextcloud
  name: nextcloud-data
  namespace: nextcloud-server
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Ti
  storageClassName: wavecat