apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud
  namespace: nextcloud-server
spec:
  replicas: 0
  selector:
    matchLabels:
      app: nextcloud
  template:
    metadata:
      labels:
        app: nextcloud
    spec:
      containers:
      - name: nextcloud
        image: lscr.io/linuxserver/nextcloud:27.0.0
        
        env:
        - name: PUID
          value: '1000'
        - name: PGID
          value: '1000'
        - name: TZ
          value: America/New_York
        ports:
        - containerPort: 443
          name: https
        volumeMounts:
        - name: config-pv
          mountPath: /config
        - name: data-pv
          mountPath: /data
      volumes:
      - name: config-pv
        persistentVolumeClaim:
          claimName: nextcloud-config
      - name: data-pv
        persistentVolumeClaim:
          claimName: nextcloud-data

