---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: media-server
  namespace: argocd
spec:
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  destinations:
    - namespace: "*"
      server: "*"
  sourceRepos:
    - "*"
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: media-server-apps
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
  project: media-server
  source:
    path: media-server
    repoURL: https://github.com/sweeneytr/wavecat.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: false
      selfHeal: true