---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: foundry-server
  namespace: argocd
spec:
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  destinations:
    - namespace: "*"
      server: "*"
  sourceRepos:
    - "*"
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: foundry-server-apps
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
  project: foundry-server
  source:
    path: foundry-server
    repoURL: https://github.com/sweeneytr/wavecat.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true