# helm repo add jetstack https://charts.jetstack.io
# helm install cert-manager jetstack/cert-manager --namespace cert-manager --create-namespace --version v1.5.1

apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    email: sweeneytri@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: issuer-account-key
    solvers:
    - selector:
        dnsZones:
          - "wavecat.net"
      dns01:
        route53:
          region: eu-east-1
          accessKeyID: AKIA4N3G6C6L3LUBM5QM
          secretAccessKeySecretRef:
            name: route53-credentials-secret
            key: secret-access-key
