ingress:
  main:
    enabled: yes
    ingressClassName: traefik
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
      traefik.ingress.kubernetes.io/router.tls: "true"
    hosts:
    - host: radarr.wavecat.net
      paths:
      - path: "/"
        pathType: Prefix
    tls:
    - hosts:
      - radarr.wavecat.net
      secretName: radarr.wavecat.net
persistance:
  config:
    enabled: true
    type: pvc
    existingClaim: radarr-pvc
    mountPath: /data