apiVersion: v1
kind: Secret
metadata:
  name: authentik-secret
  namespace: authentik
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: secret
    secret-generator.v1.mittwald.de/encoding: hex
    secret-generator.v1.mittwald.de/length: "32"