apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ingress.yaml
  - service.yaml
  - deployment.yaml

configMapGenerator:
  - name: dashy
    options:
      disableNameSuffixHash: true
      labels:
        app.kubernetes.io/name: dashy
    files:
      - dashy.yaml
