apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: vandam-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  strategy:
    type: Recreate # This makes sure only one instance is running at a time
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15.3
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-creds
              key: password
        ports:
        - containerPort: 5432
          name: psql
        volumeMounts:
        - name: data-pv
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: data-pv
        persistentVolumeClaim:
          claimName: postgres-data
          