apiVersion: v1
kind: Secret
metadata:
  name: postgres-creds
  namespace: vandam-server
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: password
    secret-generator.v1.mittwald.de/encoding: base64