apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  destination:
    namespace: cert-manager
    server: "https://kubernetes.default.svc"
  project: infra
  sources:
    - repoURL: https://charts.jetstack.io
      chart: cert-manager
      targetRevision: v1.13.2
      helm:
        releaseName: cert-manager
        values: |
          dns01RecursiveNameservers: 8.8.8.8:53,1.1.1.1:53
          dns01RecursiveNameserversOnly: True
    - repoURL: https://github.com/sweeneytr/wavecat.git
      path: infra/cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
