apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dashy
  namespace: argocd
spec:
  destination:
    namespace: dashy
    server: "https://kubernetes.default.svc"
  project: infra
  sources:
    - repoURL: https://github.com/sweeneytr/wavecat.git
      path: infra/dashy
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
