apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio
  namespace: argocd
spec:
  destination:
    namespace: istio-system
    server: "https://kubernetes.default.svc"
  project: infra
  sources:
    - repoURL: "https://istio-release.storage.googleapis.com/charts"
      chart: base
      targetRevision: 1.18.2
      helm:
        values: |
          global:
            istiod:
              enableAnalysis: true
    - repoURL: "https://istio-release.storage.googleapis.com/charts"
      chart: istiod
      targetRevision: 1.18.2
      helm:
        values: |
          pilot:
            autoscaleEnabled: false
          global:
            logAsJson: true
    - repoURL: "https://istio-release.storage.googleapis.com/charts"
      chart: gateway
      targetRevision: 1.18.2
      helm:
        values: |
          autoscaling:
            enabled: false
          imagePullPolicy: IfNotPresent
          service:
            annotations:
              metallb.universe.tf/loadBalancerIPs: 192.168.129.42
              metallb.universe.tf/ip-allocated-from-pool: first-pool
  ignoreDifferences:
    # The webhook failure policy will be updated by Istio to 'Fail' once initial testing passed
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      jqPathExpressions:
        - ".webhooks[]?.failurePolicy"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true