# https://trash-guides.info/Bazarr/Setup-Guide/
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
spec:
  destination:
    namespace: metallb-system
    server: "https://kubernetes.default.svc"
  project: infra
  source:
    repoURL: https://metallb.github.io/metallb
    chart: metallb
    targetRevision: 1.4.2
    helm:
      releaseName: metallb
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: first-pool
  namespace: metallb-system
spec:
  addresses:
  - 192.168.129.0/24
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: arp-advertisement
  namespace: metallb-system
