apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: secret-generator
  namespace: argocd
spec:
  destination:
    namespace: secret-generator
    server: https://kubernetes.default.svc
  project: infra
  sources:
    - repoURL: https://helm.mittwald.de
      chart: kubernetes-secret-generator
      targetRevision: 3.4.1
      helm:
        values: |
          image:
            pullPolicy: IfNotPresent
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true