apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zfs
  namespace: argocd
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: infra
  source:
    path: infra/zfs
    repoURL: https://github.com/sweeneytr/wavecat.git
  syncPolicy:
    automated:
      prune: true
      selfHeal: true