apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: polymer-data
  namespace: vandam-server
  labels:
    app.kubernetes.io/instance: polymer
    app.kubernetes.io/name: polymer
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 250Gi
  storageClassName: wavecat