---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
  namespace: cert-manager
spec:
  acme:
    email: sweeneytri@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: issuer-account-key
    solvers:
    - selector:
        dnsZones:
          - "wavecat.net"
      dns01:
        route53:
          region: eu-east-1
          accessKeyID: AKIA4N3G6C6LXIP4CQGW
          secretAccessKeySecretRef:
            name: route53-credentials-secret
            key: secret-access-key