apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: calibre-config
  namespace: media-server
  labels:
    app.kubernetes.io/instance: calibre
    app.kubernetes.io/name: calibre
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 250Gi
  storageClassName: wavecat