apiVersion: v1
kind: PersistentVolume
metadata:
  name: foundry-data-volume
  namespace: foundry-server
spec:
  capacity:
    storage: 16Ti
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /srv/mrgfs_foundry