apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: foundry-data-pvc
  namespace: foundry-server
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 16Ti
  storageClassName: ""
  volumeMode: Filesystem
  volumeName: foundry-data-volume
