apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: foundry-data-pvc
  namespace: foundry-server
  labels:
    app.kubernetes.io/instance: foundry
    app.kubernetes.io/name: foundry
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 250Gi
  storageClassName: wavecat
