apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - service-account.yaml
  - service.yaml
  - statefulset.yaml

configMapGenerator:
  - name: loki
    options:
      disableNameSuffixHash: true
      labels:
        app.kubernetes.io/name: loki
    files:
      - loki.yaml
