analytics:
  reporting_enabled: false

common:
  path_prefix: /data
  storage:
    filesystem:
      chunks_directory: /data/chunks
      rules_directory: /data/rules
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

server:
  grpc_server_max_recv_msg_size: 16777216

compactor:
  retention_enabled: true

limits_config:
  retention_period: 168h # 7 days
  ingestion_rate_mb: 8
  ingestion_burst_size_mb: 32
  allow_structured_metadata: true
  unordered_writes: true

# performance suggestion from: https://grafana.com/docs/loki/latest/operations/storage/filesystem/#scaling
ingester:
  max_chunk_age: 24h
  chunk_idle_period: 24h

# performance suggestion from: https://github.com/grafana/loki/blob/main/cmd/loki/loki-local-config.yaml
query_range:
  results_cache:
    cache:
      embedded_cache:
        enabled: true
        max_size_mb: 100

schema_config:
  configs:
    - from: 2023-10-25
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h
# TODO: figure out if this is needed and what it should be set to
# ruler:
#   alertmanager_url: http://localhost:9093
