apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: loki
  name: loki
spec:
  ports:
    - name: http
      port: 80
      targetPort: http
    - name: grpc
      port: 9095
  selector:
    app.kubernetes.io/name: loki
  type: ClusterIP
