apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vandam
  namespace: argocd
spec:
  destination:
    namespace:  vandam-server
    server: https://kubernetes.default.svc
  project: vandam-server
  source:
    path: vandam-server/vandam
    repoURL:  https://github.com/sweeneytr/wavecat.git
    
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
