apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-config
  namespace: media-server
  labels:
    app.kubernetes.io/instance: plex
    app.kubernetes.io/name: plex
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 250Gi
  storageClassName: wavecat