apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  app.kubernetes.io/instance: plex
  app.kubernetes.io/name: plex
  name: plex-config
  namespace: media-server
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 250Gi
  storageClassName: wavecat