apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  app.kubernetes.io/instance: filebrowser
  app.kubernetes.io/name: filebrowser
  name: filebrowser-config
  namespace: media-server
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 250Gi
  storageClassName: wavecat