apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: grafana-agent
    options:
      disableNameSuffixHash: true
      labels:
        app.kubernetes.io/name: grafana-agent
    files:
      - config.river