apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-data-volume
  namespace: nextcloud-server
spec:
  capacity:
    storage: 16Ti
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /srv/mrgfs_nextcloud