apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: foundry
  namespace: argocd
spec:
  destination:
    namespace: foundry-server
    server: https://kubernetes.default.svc
  project: foundry-server
  source:
    path: foundry-server/foundry
    repoURL:  https://github.com/sweeneytr/wavecat.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true