
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: overseerr-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: overseerr.wavecat.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: overseerr
            port:
              name: http
