apiVersion: v1
kind: PersistentVolume
metadata:
  name: config-volume
  namespace: media-server
spec:
  capacity:
    storage: 16Ti
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /srv/mrgfs_configs