apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: downloader
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
  project: media-server
  source:
    path: media-server/downloader
    repoURL: https://github.com/sweeneytr/wavecat.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: false
      selfHeal: true