apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: filebrowser
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: media-server
  sources:
    - repoURL: "https://k8s-at-home.com/charts/"
      chart: filebrowser
      targetRevision: 1.4.2
      helm:
        releaseName: filebrowser
        values: |-
          image:
            # https://github.com/filebrowser/filebrowser
            tag: v2.23.0
          env:
            TZ: America/New_York
          config: |
            {
              "port": 80,
              "baseURL": "",
              "address": "",
              "log": "stdout",
              "database": "/config/database.db",
              "root": "/data"
            }
          persistence:
            config:
              enabled: yes
              retain: yes
              accessMode: ReadWriteOnce
              existingClaim: filebrowser-config
              mountPath: /config

            media:
              enabled: yes
              retain: yes
              accessMode: ReadWriteMany
              existingClaim: media-pvc-2
              mountPath: /data
    - path: media-server/filebrowser
      repoURL:  https://github.com/sweeneytr/wavecat.git
    
  syncPolicy:
    automated:
      prune: true
      selfHeal: true