apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nzbhydra2
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: media-server
  sources:
    - repoURL: "https://k8s-at-home.com/charts/"
      targetRevision: 10.4.2
      chart: nzbhydra2
      helm:
        releaseName: nzbhydra2
        values: |-
          image:
            repository: lscr.io/linuxserver/nzbhydra2
            tag: latest
          env:
            TZ: America/New_York
            PGID: 100
          podSecurityContext:
            fsGroup: 100
            fsGroupChangePolicy: "OnRootMismatch"
          persistence:
            config:
              enabled: yes
              retain: yes
              accessMode: ReadWriteOnce
              existingClaim: nzbhydra2-config
              mountPath: /config
          probes:
            startup:
              enabled: no
            readiness:
              enabled: no
            liveness:
              enabled: no

    - path: media-server/nzbhydra2
      repoURL: https://github.com/sweeneytr/wavecat.git

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
