apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: plex
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: media-server
  sources:
    - repoURL: "https://k8s-at-home.com/charts/"
      targetRevision: 6.4.3
      chart: plex
      helm:
        releaseName: plex
        values: |-
          image:
            repository: lscr.io/linuxserver/plex
            tag: latest
          env:
            TZ: America/New_York
            PGID: 100
          podSecurityContext:
            fsGroup: 100
            fsGroupChangePolicy: "OnRootMismatch"
          ingress:
            main:
              enabled: yes
              ingressClassName: traefik
              annotations:
                cert-manager.io/cluster-issuer: letsencrypt
                traefik.ingress.kubernetes.io/router.tls: "true"
              hosts:
              - host: plex.wavecat.net
                paths:
                - path: "/"
                  pathType: Prefix
              tls:
              - hosts:
                - plex.wavecat.net
                secretName: plex.wavecat.net
          persistence:
            config:
              enabled: yes
              retain: yes
              accessMode: ReadWriteOnce
              existingClaim: plex-config
              mountPath: /config

            media:
              enabled: yes
              retain: yes
              accessMode: ReadWriteMany
              existingClaim: media-pvc-2
              mountPath: /data

    - path: media-server/plex
      repoURL: https://github.com/sweeneytr/wavecat.git

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
