apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: media-server-cluster
  namespace: media-server
spec:
  teamId: "media"
  volume:
    size: 1Gi
    storageClass: wavecat
  numberOfInstances: 1
  users:
    radarr_owner:
    - superuser
    - createdb

  patroni:
    pg_hba:
      - local     all  all  trust
      - host      all  all  0.0.0.0/0   md5
      - host      all  all  ::1/128     md5
  databases:
    radarr_main: radarr_owner
    radarr_log: radarr_owner
  postgresql:
    version: "15"
