apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: media-server-cluster
spec:
  teamId: "media"
  volume:
    size: 1Gi
    storageClass: wavecat
  numberOfInstances: 1
  users:
    radarr_owner:
    - superuser
    - createdb

  databases:
    radarr-main: radarr_owner
    radarr-log: radarr_owner
  postgresql:
    version: "15"
