apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: media-server-cluster
  namespace: media-server
spec:
  teamId: "media"
  volume:
    size: 1Gi
    storageClass: wavecat
  numberOfInstances: 1
  users:
    radarr_owner:
    - superuser
    - createdb
    lidarr_owner:
    - superuser
    - createdb
    readarr_owner:
    - superuser
    - createdb
    readarr_audio_owner:
    - superuser
    - createdb
    prowlarr_owner:
    - superuser
    - createdb
  patroni:
    # Needed for non-local non-ssl connections, needed for pgloader
    pg_hba:
      - local     all  all  trust
      - host      all  all  0.0.0.0/0   md5
      - host      all  all  ::1/128     md5
  databases:
    radarr_main: radarr_owner
    radarr_log: radarr_owner
    lidarr_main: lidarr_owner
    lidarr_log: lidarr_owner
    readarr_main: readarr_owner
    readarr_log: readarr_owner
    readarr_cache: readarr_owner
    readarr_audio_main: readarr_audio_owner
    readarr_audio_log: readarr_audio_owner
    readarr_audio_cache: readarr_audio_owner
    prowlarr_main: prowlarr_owner
    prowlarr_log: prowlarr_owner
  postgresql:
    version: "15"
