apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: radarr
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: media-server
  source:
    path: media-server/radarr
    repoURL:  https://github.com/sweeneytr/wavecat.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true