apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: readarr
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: media-server
  sources:
    - path: media-server/readarr
      repoURL: https://github.com/sweeneytr/wavecat.git
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
