apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: mesh-default
  namespace: istio-system
spec:
  selector:
    matchExpressions:
      - { key: istio-ignore, operator: DoesNotExist }
  accessLogging:
    - providers:
      - name: envoy