apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: readarr-config
  namespace: media-server
  labels:
    app.kubernetes.io/instance: readarr
    app.kubernetes.io/name: readarr
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 250Gi
  storageClassName: wavecat