apiVersion: v1
kind: Secret
metadata:
  name: readarr
  namespace: media-server
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: api-key
    secret-generator.v1.mittwald.de/encoding: hex
    secret-generator.v1.mittwald.de/length: "32"