apiVersion: v1
kind: ConfigMap
metadata:
  name: sonarr-anime-config
  namespace: media-server
data:
  config.template.xml: |
    <Config>
      <InstanceName>Sonarr (Anime)</InstanceName>
      <LogLevel>info</LogLevel>
      <UpdateMechanism>Docker</UpdateMechanism>
      <Branch>master</Branch>
      <LaunchBrowser>False</LaunchBrowser>

      <ApiKey>${API_KEY}</ApiKey>
      <AuthenticationMethod>None</AuthenticationMethod>
      <UrlBase />
      <Port>8080</Port>
      <BindAddress>*</BindAddress>
      
      <EnableSsl>False</EnableSsl>
      <SslPort>8443</SslPort>
      <SslCertPath />
      <SslCertPassword />
    </Config>