apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app.kubernetes.io/instance: mimir
    app.kubernetes.io/name: mimir
  name: mimir
spec:
  serviceName: mimir
  selector:
    matchLabels:
      app.kubernetes.io/instance: mimir
      app.kubernetes.io/name: mimir
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: mimir
        app.kubernetes.io/name: mimir
    spec:
      serviceAccountName: mimir
      securityContext:
        fsGroup: 10001
        runAsGroup: 10001
        runAsNonRoot: true
        runAsUser: 10001
      containers:
        - name: mimir
          image: "docker.io/grafana/mimir:2.10.3@sha256:20af2ec5b13339386f4e76010a44706224922df5a679ae63e996452193e668aa"
          args:
            - -config.file=/config/mimir.yaml
          ports:
            - name: http
              containerPort: 8080
            - name: grpc
              containerPort: 9095
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: [ALL]
            readOnlyRootFilesystem: true
            seccompProfile:
              type: RuntimeDefault
          readinessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 30
          volumeMounts:
            - name: config
              mountPath: /config
            - name: data
              mountPath: /data
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {}
        - name: config
          configMap:
            name: mimir
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: rpool-unsafe
        resources:
          requests:
            storage: 10Gi
