apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-config-pvc
  namespace: nextcloud-server
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 16Ti
  storageClassName: ""
  volumeMode: Filesystem
  volumeName:  nextcloud-config-volume
