apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  app.kubernetes.io/instance: overseerr
  app.kubernetes.io/name: overseerr
  name: overseerr-config
  namespace: media-server
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 250Gi
  storageClassName: wavecat