apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: overseerr-config
  namespace: media-server
  labels:
    app.kubernetes.io/instance: overseerr
    app.kubernetes.io/name: overseerr
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 250Gi
  storageClassName: wavecat