apiVersion: apps/v1
kind: Deployment
metadata:
  name: overseerr
  namespace: media-server
spec:
  selector:
    matchLabels:
      app: overseerr
  strategy:
    type: Recreate # This makes sure only one instance is running at a time
  template:
    metadata:
      labels:
        app: overseerr
    spec:
      containers:
        - name: overseerr
          image: lscr.io/linuxserver/overseerr:1.33.2
          env:
            - name: PGID
              value: "100"
            - name: TZ
              value: America/New_York
          ports:
            - containerPort: 5055
              name: http
          volumeMounts:
            - name: config-pv
              mountPath: /config
      securityContext:
        fsGroup: 100
        fsGroupChangePolicy: "OnRootMismatch"
        seccompProfile:
          type: RuntimeDefault
      volumes:
        - name: config-pv
          persistentVolumeClaim:
            claimName: overseerr-config
