apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-config
  namespace: nextcloud-server
  labels:
    app.kubernetes.io/instance: mariadb
    app.kubernetes.io/name: mariadb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 250Gi
  storageClassName: wavecat