apiVersion: v1
kind: ConfigMap
metadata:
  name: readarr-audio-config
  namespace: media-server
data:
  config.template.xml: |
    <Config>
      <InstanceName>Readarr (Audio)</InstanceName>
      <LogLevel>info</LogLevel>
      <UpdateMechanism>Docker</UpdateMechanism>
      <Branch>master</Branch>
      <LaunchBrowser>False</LaunchBrowser>

      <UrlBase />
      <ApiKey>${API_KEY}</ApiKey>
      <AuthenticationMethod>None</AuthenticationMethod>
      <Port>8080</Port>
      <BindAddress>*</BindAddress>

      <EnableSsl>False</EnableSsl>
      <SslPort>8443</SslPort>
      <SslCertPath />
      <SslCertPassword />

      <PostgresUser>${POSTGRES_USER}</PostgresUser>
      <PostgresPassword>${POSTGRES_PASSWORD}</PostgresPassword>
      <PostgresPort>${POSTGRES_PORT}</PostgresPort>
      <PostgresHost>${POSTGRES_HOST}</PostgresHost>

      <PostgresMainDb>readarr_audio_main</PostgresMainDb>
      <PostgresLogDb>readarr_audio_log</PostgresLogDb>
      <PostgresCacheDb>readarr_audio_cache</PostgresCacheDb>
    </Config>