apiVersion: apps/v1
kind: Deployment
metadata:
  name: readarr-audio
  namespace: media-server
spec:
  selector:
    matchLabels:
      app: readarr-audio
  strategy:
    type: Recreate # This makes sure only one instance is running at a time
  template:
    metadata:
      labels:
        app: readarr-audio
    spec:
      containers:
        - name: readarr-audio
          image: lscr.io/linuxserver/readarr:0.3.1-nightly
          env:
            - name: PUID
              value: "100"
            - name: PGID
              value: "100"
            - name: TZ
              value: America/New_York
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: readarr-audio-owner.media-server-cluster.credentials.postgresql.acid.zalan.do
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: readarr-audio-owner.media-server-cluster.credentials.postgresql.acid.zalan.do
                  key: password
            - name: POSTGRES_URL
              value: "postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@media-server-cluster:5432/readarr_audio_main"
          ports:
            - containerPort: 8787
              name: http
          volumeMounts:
            - name: config-pv
              mountPath: /config
            - name: data-pv
              mountPath: /data
      securityContext:
        fsGroup: 100
        fsGroupChangePolicy: "OnRootMismatch"
        seccompProfile:
          type: RuntimeDefault
      volumes:
        - name: config-pv
          persistentVolumeClaim:
            claimName: readarr-audio-config
        - name: data-pv
          persistentVolumeClaim:
            claimName: media-pvc-2
