apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: plex
  namespace: argocd
  
spec:
  project: media-server
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: media-server
  source:
    repoURL: 'https://k8s-at-home.com/charts/'
    targetRevision: 6.4.3
    chart: plex
    helm:
      releaseName: plex
      values: |-
        image:
          repository: lscr.io/linuxserver/plex
          tag: latest
        env:
          TZ: America/New_York
          PGID: 100
        podSecurityContext:
          fsGroup: 100
          fsGroupChangePolicy: "OnRootMismatch"
        ingress:
          main:
            enabled: yes
            ingressClassName: traefik
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt
              traefik.ingress.kubernetes.io/router.tls: "true"
            hosts:
            - host: plex.wavecat.net
              paths:
              - path: "/"
                pathType: Prefix
            tls:
            - hosts:
              - plex.wavecat.net
              secretName: plex.wavecat.net
        persistence:
          config:
            enabled: yes
            retain: yes
            accessMode: ReadWriteMany
            existingClaim: config-pvc
            mountPath: /config
            subPath: plex/config

          media:
            enabled: yes
            retain: yes
            accessMode: ReadWriteMany
            existingClaim: media-pvc
            mountPath: /data
