apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lidarr-config
  namespace: media-server
  labels:
    app.kubernetes.io/instance: lidarr
    app.kubernetes.io/name: lidarr
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 250Gi
  storageClassName: wavecat