apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jackett-helm
  namespace: argocd
  
spec:
  project: media-server
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: media-server
  source:
    repoURL: 'https://k8s-at-home.com/charts/'
    targetRevision: 11.7.2
    chart: jackett
    helm:
      releaseName: jackett
      values: |-
        image:
          repository: lscr.io/linuxserver/jackett
          tag: latest
        env:
          TZ: America/New_York
          PGID: 100
        podSecurityContext:
          fsGroup: 100
          fsGroupChangePolicy: "OnRootMismatch"
        ingress:
          main:
            enabled: yes
            ingressClassName: traefik
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt
              traefik.ingress.kubernetes.io/router.tls: "true"
            hosts:
            - host: jackett.wavecat.net
              paths:
              - path: "/"
                pathType: Prefix
            tls:
            - hosts:
              - jackett.wavecat.net
              secretName: jackett.wavecat.net
        persistence:
          config:
            enabled: yes
            retain: yes
            accessMode: ReadWriteOnce
            existingClaim: jackett-config
            mountPath: /config