apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jackett-config
  namespace: media-server
  labels:
    app.kubernetes.io/instance: jackett
    app.kubernetes.io/name: jackett
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 250Gi
  storageClassName: wavecat