apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: tempo
  name: tempo
spec:
  ports:
    - name: http
      port: 80
      targetPort: http
    - name: grpc
      port: 9095
    - name: otlp-grpc
      port: 4317
    - name: otlp-http
      port: 4318
  selector:
    app.kubernetes.io/name: tempo
  type: ClusterIP
