apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data
  namespace: vandam-server
  labels:
    app.kubernetes.io/instance: redis
    app.kubernetes.io/name: redis
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 250Gi
  storageClassName: wavecat